-- MySQL Script generated by MySQL Workbench
-- mié 02 dic 2020 14:32:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema InscripcionIngles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema InscripcionIngles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InscripcionIngles` ;
USE `InscripcionIngles` ;

-- -----------------------------------------------------
-- Table `InscripcionIngles`.`Semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InscripcionIngles`.`Semestre` ;

CREATE TABLE IF NOT EXISTS `InscripcionIngles`.`Semestre` (
  `idSemestre` VARCHAR(45) NOT NULL,
  `Semestre` INT NULL,
  `Carrera` VARCHAR(45) NULL,
  `Modalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idSemestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InscripcionIngles`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InscripcionIngles`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `InscripcionIngles`.`Usuario` (
  `NoControl` VARCHAR(45) NOT NULL,
  `Contrasenia` VARCHAR(45) NULL,
  `Tipo` INT NULL,
  PRIMARY KEY (`NoControl`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InscripcionIngles`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InscripcionIngles`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `InscripcionIngles`.`Profesor` (
  `NoControl` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoPaterno` VARCHAR(45) NULL,
  PRIMARY KEY (`NoControl`),
  INDEX `fk_Profesor_Usuario1_idx` (`NoControl` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_Usuario1`
    FOREIGN KEY (`NoControl`)
    REFERENCES `InscripcionIngles`.`Usuario` (`NoControl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InscripcionIngles`.`Nivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InscripcionIngles`.`Nivel` ;

CREATE TABLE IF NOT EXISTS `InscripcionIngles`.`Nivel` (
  `Grupo` VARCHAR(45) NOT NULL,
  `Nivel_idNivel` INT NULL,
  `Modalidad` VARCHAR(45) NULL,
  `Profesor_NoControl` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Grupo`, `Profesor_NoControl`),
  INDEX `fk_Nivel_Profesor1_idx` (`Profesor_NoControl` ASC) VISIBLE,
  CONSTRAINT `fk_Nivel_Profesor1`
    FOREIGN KEY (`Profesor_NoControl`)
    REFERENCES `InscripcionIngles`.`Profesor` (`NoControl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InscripcionIngles`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InscripcionIngles`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `InscripcionIngles`.`Alumno` (
  `NoControl` VARCHAR(45) NOT NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoPaterno` VARCHAR(45) NULL,
  `Semestre_idSemestre` VARCHAR(45) NOT NULL,
  `Nivel_Grupo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Semestre_idSemestre`, `Nivel_Grupo`, `NoControl`),
  INDEX `fk_Alumno_Semestre1_idx` (`Semestre_idSemestre` ASC) VISIBLE,
  INDEX `fk_Alumno_Nivel1_idx` (`Nivel_Grupo` ASC) VISIBLE,
  INDEX `fk_Alumno_Usuario1_idx` (`NoControl` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Semestre1`
    FOREIGN KEY (`Semestre_idSemestre`)
    REFERENCES `InscripcionIngles`.`Semestre` (`idSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Nivel1`
    FOREIGN KEY (`Nivel_Grupo`)
    REFERENCES `InscripcionIngles`.`Nivel` (`Grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Usuario1`
    FOREIGN KEY (`NoControl`)
    REFERENCES `InscripcionIngles`.`Usuario` (`NoControl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
